In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df["Review Rating"].value_counts()

Review Rating
3.4    182
4.0    181
4.6    170
4.2    169
3.7    168
2.9    166
3.0    162
4.9    162
3.9    162
3.8    159
2.6    158
4.4    158
3.1    156
2.7    154
3.5    152
3.2    152
4.1    148
4.7    148
3.6    147
4.3    147
3.3    146
4.8    144
4.5    139
2.8    136
5.0     68
2.5     66
Name: count, dtype: int64

In [12]:
df["Category"].value_counts()

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

In [13]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [14]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df=df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [15]:
#create a agegroup column
labels=['young adult', 'adult', 'middle-aged' , 'aged']
df["age_group"] = pd.qcut(df['age'],q=4,labels = labels)

In [16]:
df[["age","age_group"]]

      age    age_group
0      55  middle-aged
1      19  young adult
2      50  middle-aged
3      21  young adult
4      45  middle-aged
...   ...          ...
3895   40        adult
3896   52  middle-aged
3897   46  middle-aged
3898   44        adult
3899   52  middle-aged

[3900 rows x 2 columns]

In [17]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [18]:
#new columnpurchase frequency days

frequency_mapping = {
    'Every 3 Months' : 90, 
    'Annually' : 365,          
    'Quarterly' : 90,         
    'Monthly'  : 30, 
    'Bi-Weekly': 14,         
'Fortnightly' : 14,      
'Weekly' : 7  
}
df['frequency_of_purchase_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
frequency_mapping = {
     90:'Every 3 Months', 
     365 : 'Annually',          
     90:'Quarterly' ,         
     30:'Monthly'  , 
     14:'Bi-Weekly',         
 14:'Fortnightly',      
 7 : 'Weekly' 
}
df['frequency_of_purchase_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [20]:
df['frequency_of_purchase_days']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
3895    NaN
3896    NaN
3897    NaN
3898    NaN
3899    NaN
Name: frequency_of_purchase_days, Length: 3900, dtype: object

In [21]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_purchase_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle-aged,NaN
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young adult,NaN
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle-aged,NaN
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young adult,NaN
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle-aged,NaN

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'frequency_of_purchase_days'],
      dtype='object')

In [23]:
df['frequency_of_purchase_days'].value_counts()

Series([], Name: count, dtype: int64)

In [24]:
df[['frequency_of_purchase_days','frequency_of_purchases']].head(15)

   frequency_of_purchase_days frequency_of_purchases
0                         NaN            Fortnightly
1                         NaN            Fortnightly
2                         NaN                 Weekly
3                         NaN                 Weekly
4                         NaN               Annually
5                         NaN                 Weekly
6                         NaN              Quarterly
7                         NaN                 Weekly
8                         NaN               Annually
9                         NaN              Quarterly
10                        NaN              Bi-Weekly
11                        NaN            Fortnightly
12                        NaN            Fortnightly
13                        NaN                 Weekly
14                        NaN                 Weekly

In [25]:
df[['discount_applied', 'promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [26]:
(df['discount_applied']==df['promo_code_used']).all()

True

In [27]:
df = df.drop('promo_code_used',axis = 1)

In [28]:
df = df.drop('discount_applied',axis = 1)

In [29]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'previous_purchases', 'payment_method', 'frequency_of_purchases',
       'age_group', 'frequency_of_purchase_days'],
      dtype='object')

In [30]:
       # steps

# import dataset
# df.head()
#df.tail()
#df.info()
#df.describe()
#df.describe(include = all)               -> describe all categorical and numerical
#df.isnull().sum()                        -> null values
#df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))              
                                         #-> -> remove null values using with median by group wise
# df[" "].value_counts()                  -> see distinct values by group wise
# convert all columns into snake case(small letterwith underscore)
# df[["age_group"]]                 -> add newcolumns used with qcut
# add another column frequency days
#remove unnecessary columns

In [31]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\sanap\anaconda3\lib\site-packages (9.4.0)

In [32]:
import sys
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\sanap\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: psycopg2-binary in c:\users\sanap\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [33]:
from sqlalchemy import create_engine

In [34]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\sanap\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\sanap\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [35]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\sanap\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\sanap\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sanap\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [37]:
frequency_mapping = {
     'Every 3 Months' : 90, 
      'Annually' : 365,          
     'Quarterly': 90 ,         
     'Monthly': 30  , 
     'Bi-Weekly':14,         
 'Fortnightly': 14,      
  'Weekly':7 
}
df['frequency_of_purchase_day']=df['frequency_of_purchases'].map(frequency_mapping)

In [38]:
df['frequency_of_purchase_day']

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: frequency_of_purchase_day, Length: 3900, dtype: int64

In [39]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'previous_purchases', 'payment_method', 'frequency_of_purchases',
       'age_group', 'frequency_of_purchase_days', 'frequency_of_purchase_day'],
      dtype='object')

In [40]:
df.drop ('frequency_of_purchase_days',axis=1)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_purchase_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,14,Venmo,Fortnightly,middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,2,Cash,Fortnightly,young adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,23,Credit Card,Weekly,middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,49,PayPal,Weekly,young adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,31,PayPal,Annually,middle-aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,32,Venmo,Weekly,adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,41,Bank Transfer,Bi-Weekly,middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,24,Venmo,Quarterly,middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,24,Venmo,Weekly,adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,33,Venmo,Quarterly,middle-aged,90

In [42]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = quote_plus("Gowtham@6134")
host = "localhost"
port = 3306
database = "customer_shopping_behavior"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

table_name="mytable"
df.to_sql(table_name,engine,if_exists="replace",index = False)

pd.read_sql("SELECT * from mytable LIMIT 5;",engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_of_purchase_days,frequency_of_purchase_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,14,Venmo,Fortnightly,middle-aged,None,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,2,Cash,Fortnightly,young adult,None,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,23,Credit Card,Weekly,middle-aged,None,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,49,PayPal,Weekly,young adult,None,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,31,PayPal,Annually,middle-aged,None,365